language: java
sudo: true
jdk: openjdk8
addons:
  sonarcloud:
    organization: ads-org
    token:
      secure: TSejE2fTRxUcEBz2pBvmNUD8C3JHYyW/TJ2IsZTncGKxwZoqe4ekGZbH23glr7RgTlB+96djoEjd1j6B9NodnUCTN04t2BlxAN8hPsQWF4jEFFAdHCBQ9Bir51L1C3jq/ZCGxrgRkRYdnjWYWj0LsTzic3SgaUUC43ojvuME+5rB1fz6u+V5kxcHpd/O9XWZRJ3+BR8tWmloHdQFN/Ys1+mdKIvwmhaiMV1wtFg069MMcpJJN5jRwwzKHnAR3A7oAwSTTNj67eJkPqUvL9n9iO012OPYuWlSqeYHiLFyom1vmP7mvoKSPoASVpCRAMZNq9gYow+gXFVgjdv9lWKZDqMfh+0KWP/7zdAZbK3DmQxeAd25pAj+rrQZ2nUwlB8V0ii/aY3DsG8E5SpfHPsgaNMqzFkufFGYfB8F/HI9wSt8/wbO/KjdwFGFzLOVNw3CX/seRy7DR/GoGdUPw2bIUp0nsLYQe/HPlJsVMd+O1zRXAn+8xfG7W+dp/ZHxFtpPDCtVg7prQX05xeaHFuPj0mtaJNWtI4ANVN+6FjYSpMtfLJSELij6Uysy7LGgSZCS6KCpjlKSSTYxQxxQoPDrhYebamr/N37KHJq1939BbNrm8/FUTJ6s5o5SEHo9EHNW05k5koICiMlN8/INQflvsmMnKosqWbAgBwpdZTVAStI=
script: env && ./mvnw package -B sonar:sonar
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: buqADz3dOqEEQkOlDyMJE/2JNFNkYlIns3ZatmM96RxX2NCFIP3GoVVju0cmivLc7oGrL2OupsfJhaaPoV+CdNQIi6HZ0Y5Jpr/8QMtEblodmOBxQf9wZsnWAsLGiy9cusETyukd7S3FrGnI8Tg57AxZCCHulTWmRqteU7NnkIp4Nq7CMHV2Nqi+6/Vbf+DKqHg6zCrtJ7fOHZyJ+aQ4k76W61KXkvWX3E2s4qyZ6LEdYwuGmkstodU4L4pGZAYEz9hCxhXfDzdEgoY63JqmgeoK5jMvYYZrPp1+/pcWGsMiT5No4tQhQFdsfxIWXy1je9Gvuq2hU1DvpPxSshOq77OKs1a11eLW+Nh8C2ThHEiS8X1Y6wsT//a/OEq/iZNC6MpsM7Crj7tW7BTmY1eXsQj4qS88XMbayasmhnKWNyasI40pIRwt6itGjGGBDOXfrze8K8crpsvYOqTkM1CV427AvI5duva5xFo/ATvNYZhM2Z+eM2pddKwouV7inqv0CGqHYNKOEyUfAiKi6jgiSCPE1fqF63FfsNTLAIU97MpkVRpRh3dQ/2BFLctMJ0SKzDCkM7+iFfTZo2X9J1IU14Kpzr/KutGlFT6WsV1lZhGJDrZSxNUtLm7Hilu3Z0GabiWf7Zm/e51Y/lJ2iwOCaX81n148zoJtZ7dUf9UNBdQ=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: production
