language: java
sudo: true
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: ads-org
    token:
      secure: esUFcuR7wLEKeksymUyynY+LSyXUwSA4/EkfDgQBqb4+nt/Sr0jPFNhtXffQ5HZsbHZYBT09+XAeEBbcSYcc7Je0qRXUV69xmObJB56H4mtn8/GxERo97/uF1G+Upq/QD5rQGlrlg1YzFawqz+Zjhkn8fCcJXMgid+cAS9fzN6AxLz8H39vkWDVT+yZQ/KvQVl+mDdOpQsgl6RhXUCPdnrnDlr8Kv0tzO4DAUw+wy/0hf7wo6dzrJNGKfeyIesUKzT8NDJbwvVMaj5mx6P7d/NqfsPz99DWbyipHjx6lPFMBYOif4/nm+f01XQcpT3dGT3IpMwUQpNls2U11PR5dARxb2dLjvyEWyyc8rwawWTd16oLKNVfC9okjaQ3m4nwQNdK9pa53K8l71230lRlBGuHPZ19GsUbV66Lw8NzJirCtm6UTDb1elL6a64vVzQ5bOzxJl0aK8PWSHIBeszcyQ4U9DgonadNP83JvSNaPcGyJGArE+TgAGEjVdGtrlEZvxEn3HZ4rzBzJJBMMXThcXamo2X350IGDZ/xJCCuDl3y0EUT+Ul0t9Mg5se4/6NOPTr/2tvFj5rbYA1JDeouKDjHdiHo9ZSQlrm/GkQHtOv0bfvz47lF6meajbIrWncQ3PckkuoSzWzpe3yeOrOIo9pSNqoWro2i6LsH/1YszDpo=
script: env && ./mvnw package -B sonar:sonar
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: buqADz3dOqEEQkOlDyMJE/2JNFNkYlIns3ZatmM96RxX2NCFIP3GoVVju0cmivLc7oGrL2OupsfJhaaPoV+CdNQIi6HZ0Y5Jpr/8QMtEblodmOBxQf9wZsnWAsLGiy9cusETyukd7S3FrGnI8Tg57AxZCCHulTWmRqteU7NnkIp4Nq7CMHV2Nqi+6/Vbf+DKqHg6zCrtJ7fOHZyJ+aQ4k76W61KXkvWX3E2s4qyZ6LEdYwuGmkstodU4L4pGZAYEz9hCxhXfDzdEgoY63JqmgeoK5jMvYYZrPp1+/pcWGsMiT5No4tQhQFdsfxIWXy1je9Gvuq2hU1DvpPxSshOq77OKs1a11eLW+Nh8C2ThHEiS8X1Y6wsT//a/OEq/iZNC6MpsM7Crj7tW7BTmY1eXsQj4qS88XMbayasmhnKWNyasI40pIRwt6itGjGGBDOXfrze8K8crpsvYOqTkM1CV427AvI5duva5xFo/ATvNYZhM2Z+eM2pddKwouV7inqv0CGqHYNKOEyUfAiKi6jgiSCPE1fqF63FfsNTLAIU97MpkVRpRh3dQ/2BFLctMJ0SKzDCkM7+iFfTZo2X9J1IU14Kpzr/KutGlFT6WsV1lZhGJDrZSxNUtLm7Hilu3Z0GabiWf7Zm/e51Y/lJ2iwOCaX81n148zoJtZ7dUf9UNBdQ=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: production
